# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Traversier.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QDateEdit, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1916, 1066)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 1920, 1080))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.calendarWidget = QCalendarWidget(self.tab)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(340, 240, 1081, 581))
        self.Accueil = QLabel(self.tab)
        self.Accueil.setObjectName(u"Accueil")
        self.Accueil.setGeometry(QRect(830, 10, 211, 41))
        font = QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.Accueil.setFont(font)
        self.tabWidget.addTab(self.tab, "")
        self.Personne = QWidget()
        self.Personne.setObjectName(u"Personne")
        self.adresseClient = QLineEdit(self.Personne)
        self.adresseClient.setObjectName(u"adresseClient")
        self.adresseClient.setGeometry(QRect(580, 280, 361, 41))
        self.label = QLabel(self.Personne)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(470, 170, 101, 20))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(True)
        self.label.setFont(font1)
        self.provienceClient = QLineEdit(self.Personne)
        self.provienceClient.setObjectName(u"provienceClient")
        self.provienceClient.setGeometry(QRect(580, 400, 361, 41))
        self.label_3 = QLabel(self.Personne)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(470, 350, 101, 21))
        self.label_3.setFont(font1)
        self.villeClient = QLineEdit(self.Personne)
        self.villeClient.setObjectName(u"villeClient")
        self.villeClient.setGeometry(QRect(580, 340, 361, 41))
        self.courrielClient = QLineEdit(self.Personne)
        self.courrielClient.setObjectName(u"courrielClient")
        self.courrielClient.setGeometry(QRect(580, 580, 361, 41))
        self.codePostalClient = QLineEdit(self.Personne)
        self.codePostalClient.setObjectName(u"codePostalClient")
        self.codePostalClient.setGeometry(QRect(580, 460, 361, 41))
        self.label_7 = QLabel(self.Personne)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(470, 590, 101, 20))
        self.label_7.setFont(font1)
        self.label_6 = QLabel(self.Personne)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(430, 520, 141, 41))
        self.label_6.setFont(font1)
        self.telephoneClient = QLineEdit(self.Personne)
        self.telephoneClient.setObjectName(u"telephoneClient")
        self.telephoneClient.setGeometry(QRect(580, 520, 361, 41))
        self.label_8 = QLabel(self.Personne)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(920, 10, 211, 41))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.label_8.setFont(font2)
        self.label_5 = QLabel(self.Personne)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(430, 460, 141, 41))
        self.label_5.setFont(font1)
        self.nomClient = QLineEdit(self.Personne)
        self.nomClient.setObjectName(u"nomClient")
        self.nomClient.setGeometry(QRect(580, 160, 361, 41))
        self.label_4 = QLabel(self.Personne)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(440, 400, 131, 41))
        self.label_4.setFont(font1)
        self.label_2 = QLabel(self.Personne)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(470, 290, 101, 16))
        self.label_2.setFont(font1)
        self.listeClient = QListWidget(self.Personne)
        self.listeClient.setObjectName(u"listeClient")
        self.listeClient.setGeometry(QRect(1440, 150, 411, 761))
        self.label_9 = QLabel(self.Personne)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(570, 120, 151, 16))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        self.label_9.setFont(font3)
        self.label_10 = QLabel(self.Personne)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1440, 130, 241, 16))
        self.label_10.setFont(font3)
        self.btnClient = QPushButton(self.Personne)
        self.btnClient.setObjectName(u"btnClient")
        self.btnClient.setGeometry(QRect(620, 840, 281, 61))
        self.numClient = QLineEdit(self.Personne)
        self.numClient.setObjectName(u"numClient")
        self.numClient.setGeometry(QRect(580, 640, 361, 41))
        self.label_38 = QLabel(self.Personne)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(410, 650, 161, 20))
        self.label_38.setFont(font1)
        self.sexeClient = QLineEdit(self.Personne)
        self.sexeClient.setObjectName(u"sexeClient")
        self.sexeClient.setGeometry(QRect(580, 700, 361, 41))
        self.dateNaissance = QDateEdit(self.Personne)
        self.dateNaissance.setObjectName(u"dateNaissance")
        self.dateNaissance.setGeometry(QRect(580, 760, 361, 41))
        self.label_39 = QLabel(self.Personne)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(440, 710, 131, 20))
        self.label_39.setFont(font1)
        self.label_40 = QLabel(self.Personne)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(410, 770, 161, 20))
        self.label_40.setFont(font1)
        self.btnClient_2 = QPushButton(self.Personne)
        self.btnClient_2.setObjectName(u"btnClient_2")
        self.btnClient_2.setGeometry(QRect(1520, 920, 281, 51))
        self.prenomClient = QLineEdit(self.Personne)
        self.prenomClient.setObjectName(u"prenomClient")
        self.prenomClient.setGeometry(QRect(580, 220, 361, 41))
        self.label_41 = QLabel(self.Personne)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(470, 230, 101, 20))
        self.label_41.setFont(font1)
        self.tabWidget.addTab(self.Personne, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_21 = QLabel(self.tab_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(840, 0, 321, 101))
        self.label_21.setFont(font2)
        self.label_22 = QLabel(self.tab_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(450, 160, 211, 51))
        self.label_22.setFont(font3)
        self.label_23 = QLabel(self.tab_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(400, 210, 91, 31))
        self.label_23.setFont(font1)
        self.nomEmploye = QLineEdit(self.tab_4)
        self.nomEmploye.setObjectName(u"nomEmploye")
        self.nomEmploye.setGeometry(QRect(500, 210, 361, 41))
        self.label_24 = QLabel(self.tab_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(1440, 120, 171, 51))
        self.label_24.setFont(font3)
        self.listeEmploye = QListWidget(self.tab_4)
        self.listeEmploye.setObjectName(u"listeEmploye")
        self.listeEmploye.setGeometry(QRect(1440, 160, 411, 761))
        self.label_25 = QLabel(self.tab_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(380, 330, 111, 20))
        self.label_25.setFont(font1)
        self.label_26 = QLabel(self.tab_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(400, 390, 91, 20))
        self.label_26.setFont(font1)
        self.label_27 = QLabel(self.tab_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(370, 450, 111, 20))
        self.label_27.setFont(font1)
        self.label_28 = QLabel(self.tab_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(370, 510, 111, 20))
        self.label_28.setFont(font1)
        self.label_29 = QLabel(self.tab_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(370, 570, 111, 20))
        self.label_29.setFont(font1)
        self.label_30 = QLabel(self.tab_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(370, 630, 121, 20))
        self.label_30.setFont(font1)
        self.adresseEmploye = QLineEdit(self.tab_4)
        self.adresseEmploye.setObjectName(u"adresseEmploye")
        self.adresseEmploye.setGeometry(QRect(500, 320, 361, 41))
        self.villeEmploye = QLineEdit(self.tab_4)
        self.villeEmploye.setObjectName(u"villeEmploye")
        self.villeEmploye.setGeometry(QRect(500, 380, 361, 41))
        self.provinceEmploye = QLineEdit(self.tab_4)
        self.provinceEmploye.setObjectName(u"provinceEmploye")
        self.provinceEmploye.setGeometry(QRect(500, 440, 361, 41))
        self.codePostalEmploye = QLineEdit(self.tab_4)
        self.codePostalEmploye.setObjectName(u"codePostalEmploye")
        self.codePostalEmploye.setGeometry(QRect(500, 500, 361, 41))
        self.telephoneEmploye = QLineEdit(self.tab_4)
        self.telephoneEmploye.setObjectName(u"telephoneEmploye")
        self.telephoneEmploye.setGeometry(QRect(500, 560, 361, 41))
        self.courrielEmploye = QLineEdit(self.tab_4)
        self.courrielEmploye.setObjectName(u"courrielEmploye")
        self.courrielEmploye.setGeometry(QRect(500, 620, 361, 41))
        self.label_31 = QLabel(self.tab_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(380, 690, 111, 20))
        self.label_31.setFont(font1)
        self.nasEmploye = QLineEdit(self.tab_4)
        self.nasEmploye.setObjectName(u"nasEmploye")
        self.nasEmploye.setGeometry(QRect(500, 680, 361, 41))
        self.btnEmploye = QPushButton(self.tab_4)
        self.btnEmploye.setObjectName(u"btnEmploye")
        self.btnEmploye.setGeometry(QRect(550, 750, 281, 61))
        self.prenomEmploye = QLineEdit(self.tab_4)
        self.prenomEmploye.setObjectName(u"prenomEmploye")
        self.prenomEmploye.setGeometry(QRect(500, 260, 361, 41))
        self.label_42 = QLabel(self.tab_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(400, 270, 91, 31))
        self.label_42.setFont(font1)
        self.btnEmploye_2 = QPushButton(self.tab_4)
        self.btnEmploye_2.setObjectName(u"btnEmploye_2")
        self.btnEmploye_2.setGeometry(QRect(1510, 940, 281, 61))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(890, 20, 311, 41))
        self.label_11.setFont(font2)
        self.label_44 = QLabel(self.tab_2)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(1440, 180, 181, 16))
        self.label_44.setFont(font3)
        self.listeVoiture = QListWidget(self.tab_2)
        self.listeVoiture.setObjectName(u"listeVoiture")
        self.listeVoiture.setGeometry(QRect(1440, 220, 411, 761))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(500, 170, 181, 16))
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(510, 230, 71, 20))
        self.label_13.setFont(font1)
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(510, 290, 71, 20))
        self.label_14.setFont(font1)
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(510, 350, 71, 20))
        self.label_15.setFont(font1)
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(510, 410, 71, 20))
        self.label_16.setFont(font1)
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(410, 470, 161, 20))
        self.label_17.setFont(font1)
        self.marqueVoiture = QLineEdit(self.tab_2)
        self.marqueVoiture.setObjectName(u"marqueVoiture")
        self.marqueVoiture.setGeometry(QRect(590, 220, 361, 41))
        self.modeleVoiture = QLineEdit(self.tab_2)
        self.modeleVoiture.setObjectName(u"modeleVoiture")
        self.modeleVoiture.setGeometry(QRect(590, 280, 361, 41))
        self.couleurVoiture = QLineEdit(self.tab_2)
        self.couleurVoiture.setObjectName(u"couleurVoiture")
        self.couleurVoiture.setGeometry(QRect(590, 340, 361, 41))
        self.immatriculationVoiture = QLineEdit(self.tab_2)
        self.immatriculationVoiture.setObjectName(u"immatriculationVoiture")
        self.immatriculationVoiture.setGeometry(QRect(590, 460, 361, 41))
        self.btnVoiture = QPushButton(self.tab_2)
        self.btnVoiture.setObjectName(u"btnVoiture")
        self.btnVoiture.setGeometry(QRect(640, 730, 281, 61))
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(410, 530, 171, 20))
        self.label_18.setFont(font1)
        self.typeVoiture = QLineEdit(self.tab_2)
        self.typeVoiture.setObjectName(u"typeVoiture")
        self.typeVoiture.setGeometry(QRect(590, 520, 361, 41))
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(410, 590, 171, 20))
        self.label_19.setFont(font1)
        self.nbRoueVoiture = QLineEdit(self.tab_2)
        self.nbRoueVoiture.setObjectName(u"nbRoueVoiture")
        self.nbRoueVoiture.setGeometry(QRect(590, 580, 361, 41))
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(410, 650, 171, 20))
        self.label_20.setFont(font1)
        self.prixTraverseVoiture = QLineEdit(self.tab_2)
        self.prixTraverseVoiture.setObjectName(u"prixTraverseVoiture")
        self.prixTraverseVoiture.setGeometry(QRect(590, 640, 361, 41))
        self.dateVoiture = QDateEdit(self.tab_2)
        self.dateVoiture.setObjectName(u"dateVoiture")
        self.dateVoiture.setGeometry(QRect(590, 400, 361, 41))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_32 = QLabel(self.tab_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(760, 10, 301, 41))
        self.label_32.setFont(font2)
        self.listeVoiture_4 = QLabel(self.tab_3)
        self.listeVoiture_4.setObjectName(u"listeVoiture_4")
        self.listeVoiture_4.setGeometry(QRect(1480, 170, 201, 20))
        self.listeVoiture_4.setFont(font3)
        self.listeTraversier = QListWidget(self.tab_3)
        self.listeTraversier.setObjectName(u"listeTraversier")
        self.listeTraversier.setGeometry(QRect(1470, 220, 411, 761))
        self.label_33 = QLabel(self.tab_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(270, 180, 221, 16))
        self.label_33.setFont(font3)
        self.label_34 = QLabel(self.tab_3)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(240, 230, 101, 20))
        self.label_34.setFont(font1)
        self.nomTraversier = QLineEdit(self.tab_3)
        self.nomTraversier.setObjectName(u"nomTraversier")
        self.nomTraversier.setGeometry(QRect(400, 220, 361, 41))
        self.label_35 = QLabel(self.tab_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(180, 290, 211, 20))
        self.label_35.setFont(font1)
        self.capaVehiculeTraversier = QLineEdit(self.tab_3)
        self.capaVehiculeTraversier.setObjectName(u"capaVehiculeTraversier")
        self.capaVehiculeTraversier.setGeometry(QRect(400, 280, 361, 41))
        self.label_36 = QLabel(self.tab_3)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(180, 350, 211, 20))
        self.label_36.setFont(font1)
        self.capaPersonneTraversier = QLineEdit(self.tab_3)
        self.capaPersonneTraversier.setObjectName(u"capaPersonneTraversier")
        self.capaPersonneTraversier.setGeometry(QRect(400, 340, 361, 41))
        self.label_37 = QLabel(self.tab_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(180, 410, 201, 20))
        self.label_37.setFont(font1)
        self.dateTraversier = QDateEdit(self.tab_3)
        self.dateTraversier.setObjectName(u"dateTraversier")
        self.dateTraversier.setGeometry(QRect(400, 400, 361, 41))
        self.listeEmployerTraversier = QListWidget(self.tab_3)
        self.listeEmployerTraversier.setObjectName(u"listeEmployerTraversier")
        self.listeEmployerTraversier.setGeometry(QRect(1040, 220, 411, 761))
        self.listeVoiture_7 = QLabel(self.tab_3)
        self.listeVoiture_7.setObjectName(u"listeVoiture_7")
        self.listeVoiture_7.setGeometry(QRect(1040, 170, 281, 21))
        self.listeVoiture_7.setFont(font3)
        self.btnTraversier = QPushButton(self.tab_3)
        self.btnTraversier.setObjectName(u"btnTraversier")
        self.btnTraversier.setGeometry(QRect(430, 510, 281, 61))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_43 = QLabel(self.tab_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(940, 10, 301, 41))
        self.label_43.setFont(font2)
        self.listeEmployerTraversier_2 = QListWidget(self.tab_5)
        self.listeEmployerTraversier_2.setObjectName(u"listeEmployerTraversier_2")
        self.listeEmployerTraversier_2.setGeometry(QRect(1030, 120, 411, 761))
        self.listeEmployerTraversier_3 = QListWidget(self.tab_5)
        self.listeEmployerTraversier_3.setObjectName(u"listeEmployerTraversier_3")
        self.listeEmployerTraversier_3.setGeometry(QRect(1470, 120, 411, 761))
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Accueil.setText(QCoreApplication.translate("MainWindow", u"Accueil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Accueil", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Nom", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Ville", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Courriel", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"T\u00e9l\u00e9phone", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Client", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Code postale", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Province ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Adresse", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Inscription :", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Liste client :", None))
        self.btnClient.setText(QCoreApplication.translate("MainWindow", u"Soumettre", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Num\u00e9ro d'identification", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Sexe", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Date de naissance", None))
        self.btnClient_2.setText(QCoreApplication.translate("MainWindow", u"Supprimer", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Prenom", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Personne), QCoreApplication.translate("MainWindow", u"Client", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Employ\u00e9", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Inscription :", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Nom", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Liste employ\u00e9s :", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Adresse", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Ville", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Province", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Code postal", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"T\u00e9l\u00e9phone", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Courriel", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"NAS", None))
        self.btnEmploye.setText(QCoreApplication.translate("MainWindow", u"Soumettre", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Prenom", None))
        self.btnEmploye_2.setText(QCoreApplication.translate("MainWindow", u"Supprimer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Employ\u00e9", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Voiture", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Liste Voiture:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Inscription :", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Marque", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Mod\u00e8le", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Couleur", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Ann\u00e9e", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Immatriculation", None))
        self.btnVoiture.setText(QCoreApplication.translate("MainWindow", u"Soumettre", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"nom du type de v\u00e9hicule", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Nombre de roue", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"PrixTraverse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Voiture", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Traversier", None))
        self.listeVoiture_4.setText(QCoreApplication.translate("MainWindow", u"Liste traversier:", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Inscription :", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Nom", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Capacit\u00e9 vehicule", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Capacit\u00e9 personne", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Date mise en service", None))
        self.listeVoiture_7.setText(QCoreApplication.translate("MainWindow", u"Liste employ\u00e9s:", None))
        self.btnTraversier.setText(QCoreApplication.translate("MainWindow", u"Soumettre", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Traversier", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Traverse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Traverse", None))
    # retranslateUi

